In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [20]:
#zero dimentional array
arr=np.array(40)
print(arr)
print(arr.ndim)

40
0


In [19]:
#one dimensional array
arr=np.array([10,20,30,40,50])
arr
print(arr.ndim)

1


In [21]:
#two dimensional array
arr=np.array([[1,2,3],
             [4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [24]:
#three dimensional array
arr=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr)
print(arr.ndim)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
3


In [30]:
#"sicing"
arr=np.array([10,20,30,40,50,60])
arr
print(arr[1:5])
#sicing with intervals
print(arr[1:6:2])

[20 30 40 50]
[20 40 60]


In [31]:
#negative slicing 
print(arr[-1])

60


In [32]:
print(arr[-3:-1])

[40 50]


In [35]:
print(arr[-4:-1])

[30 40 50]


In [36]:
#checking data types of array
print(arr.dtype)

int32


In [37]:
#checking shape
print(arr.shape)

(6,)


In [38]:
#checking size
print(arr.size)

6


In [39]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [42]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [45]:
#spliting array
arr=np.array([1,2,3,4,5,6])
new_arr=np.array_split(arr,6)   #divides the array elements in rows & if the count is more than the elements then it return values null 
print(new_arr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [46]:
#searching for an index of element
x=np.where(arr==5)
x

(array([4], dtype=int64),)

In [47]:
#sorting array
abc=np.array([3,7,1,9,2,6])
print(np.sort(abc))

[1 2 3 6 7 9]


In [48]:
#filtering array
arr=np.array([1,2,3,4])
x=[True,False,True,False]
new_arr=arr[x]
print(new_arr)

[1 3]


In [50]:
arr=np.array([26,11,30,45])
filter_arr=[]
for element in arr:
    if element>28:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr=arr[filter_arr]
print(filter_arr)
print(new_arr)

[False, False, True, True]
[30 45]


In [52]:
#conversing the datetype
arr=np.array([1,2,3,4,5,6])
#print(np.astype(str))

In [53]:
#adding and removing elements
arr=np.array([1,2,3,4,5,6])
print(arr)
print(np.append(arr,7))

[1 2 3 4 5 6]
[1 2 3 4 5 6 7]


In [54]:
#inserting
print(np.insert(arr,3,8))

[1 2 3 8 4 5 6]


In [55]:
#deleting elemnts
print(np.delete(arr,[1]))

[1 3 4 5 6]


In [9]:
#Aggregate function
arr=np.array([10,20,30,40,50])
print("Array : ",arr)

#sum
print("Sum of array : ",np.sum(arr))

#minimum
print("min value : ",np.min(arr))

#maximum
print("max value : ",np.max(arr))

#cumulative sum
print("cumsum : ",np.cumsum(arr))

Array :  [10 20 30 40 50]
Sum of array :  150
min value :  10
max value :  50
cumsum :  [ 10  30  60 100 150]


In [6]:
import statistics as stats
food_prices=[100,200,400,500,300,200]
a=np.array(food_prices)

#mean
print("mean : ",np.mean(a))

#median
print("median : ",np.median(a))

#mode
print("mode : ",stats.mode(a))

#SD
print("Standard Deviation : ",np.std(a))

mean :  283.3333333333333
median :  250.0
mode :  200
Standard Deviation :  134.3709624716425
